# Generated by Django 2.2.4 on 2019-08-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosk', '0003_currentorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentorder',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
